FROM ghcr.io/kamailio/kamailio:5.8.0-bookworm
ENV SHM_MEMORY=${SHM_MEMORY:-64}
ENV PKG_MEMORY=${PKG_MEMORY:-8}
RUN apt update && apt install wget \
    && wget https://github.com/sipcapture/rtcagent/releases/latest/download/rtcagent \
    && chmod +x /rtcagent \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ENTRYPOINT kamailio -DD -E -m ${SHM_MEMORY} -M ${PKG_MEMORY} & /rtcagent kamailio -m /usr/sbin/kamailio
